# Generated by Django 5.0 on 2026-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="url",
            field=models.URLField(blank=True, verbose_name="分类链接"),
        ),
    ]
