# Generated by Django 5.0 on 2026-02-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_category_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0, verbose_name="排序"),
        ),
    ]
