# Generated by Django 5.0 on 2026-02-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_alter_category_options_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="浏览次数"),
        ),
    ]
