# Generated by Django 5.0 on 2026-02-28 04:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0004_tool_view_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="专题标题")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="URL标识"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(max_length=300, verbose_name="SEO描述"),
                ),
                ("intro", models.TextField(blank=True, verbose_name="专题介绍")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否发布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="topic_pages",
                        to="tools.category",
                        verbose_name="关联分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "专题页",
                "verbose_name_plural": "专题页",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolDailyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="日期"
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_views",
                        to="tools.tool",
                        verbose_name="工具",
                    ),
                ),
            ],
            options={
                "verbose_name": "工具日浏览",
                "verbose_name_plural": "工具日浏览",
                "ordering": ["-date", "-count"],
                "unique_together": {("tool", "date")},
            },
        ),
    ]
