# Generated by Django 5.0 on 2026-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_topicpage_tooldailyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=32, unique=True, verbose_name='订单号')),
                ('contact_name', models.CharField(max_length=80, verbose_name='联系人')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('wechat', models.CharField(blank=True, max_length=80, verbose_name='微信/Telegram')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='公司/品牌')),
                ('source_text', models.TextField(verbose_name='待转文本')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('voice_preset', models.CharField(choices=[('sweet_vivian', '甜美女声 Vivian'), ('gentle_serena', '温柔知性 Serena'), ('youthful_ono', '年轻活力 Ono Anna'), ('custom', '定制风格')], default='sweet_vivian', max_length=32, verbose_name='音色方案')),
                ('style_notes', models.CharField(blank=True, max_length=240, verbose_name='补充风格要求')),
                ('business_usage', models.BooleanField(default=True, verbose_name='商业用途授权')),
                ('delivery_format', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV')], default='mp3', max_length=8, verbose_name='交付格式')),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='系统报价')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最终成交价')),
                ('status', models.CharField(choices=[('pending_payment', '待付款'), ('queued', '待生成'), ('generating', '生成中'), ('delivered', '已交付'), ('cancelled', '已取消')], default='pending_payment', max_length=24, verbose_name='订单状态')),
                ('payment_status', models.CharField(choices=[('unpaid', '未付款'), ('paid', '已付款'), ('refunded', '已退款')], default='unpaid', max_length=24, verbose_name='支付状态')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='tts_orders/', verbose_name='生成音频')),
                ('output_duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='音频时长（秒）')),
                ('processing_log', models.TextField(blank=True, verbose_name='处理日志')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='交付时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'TTS订单',
                'verbose_name_plural': 'TTS订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
