# Generated by Django 5.0 on 2026-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_ttsorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttsorder',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='tts_payment_proofs/', verbose_name='支付凭证'),
        ),
        migrations.AddField(
            model_name='ttsorder',
            name='payment_proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付凭证上传时间'),
        ),
    ]
