# Generated by Django 5.0 on 2026-03-12 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0008_ttsorder_auto_payment_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ttsorder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tts_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.CreateModel(
            name="TTSCreditAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_balance",
                    models.PositiveIntegerField(default=0, verbose_name="剩余字数额度"),
                ),
                (
                    "total_purchased_chars",
                    models.PositiveIntegerField(default=0, verbose_name="累计购买字数"),
                ),
                (
                    "total_used_chars",
                    models.PositiveIntegerField(default=0, verbose_name="累计消费字数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tts_credit_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "TTS额度账户",
                "verbose_name_plural": "TTS额度账户",
            },
        ),
        migrations.CreateModel(
            name="TTSCreditRechargeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        unique=True,
                        verbose_name="充值订单号",
                    ),
                ),
                (
                    "char_amount",
                    models.PositiveIntegerField(default=0, verbose_name="充值字数"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="充值金额",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未付款"),
                            ("paid", "已付款"),
                            ("refunded", "已退款"),
                        ],
                        default="unpaid",
                        max_length=24,
                        verbose_name="支付状态",
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        choices=[("alipay", "支付宝"), ("wechat", "微信支付")],
                        max_length=16,
                        verbose_name="支付渠道",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="渠道流水号"
                    ),
                ),
                (
                    "payment_note_token",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        unique=True,
                        verbose_name="付款备注码",
                    ),
                ),
                (
                    "payment_callback_payload",
                    models.JSONField(
                        blank=True, null=True, verbose_name="支付回调载荷"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="付款时间"
                    ),
                ),
                (
                    "payment_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="支付核验时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tts_recharge_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "TTS充值订单",
                "verbose_name_plural": "TTS充值订单",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TTSCreditLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("recharge", "充值"),
                            ("consume", "消费"),
                            ("refund", "退款"),
                        ],
                        max_length=24,
                        verbose_name="流水类型",
                    ),
                ),
                ("char_delta", models.IntegerField(verbose_name="字数变动")),
                (
                    "balance_after",
                    models.PositiveIntegerField(verbose_name="变动后余额"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "tts_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="tools.ttsorder",
                        verbose_name="关联TTS订单",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tts_credit_ledgers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "recharge_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="tools.ttscreditrechargeorder",
                        verbose_name="关联充值单",
                    ),
                ),
            ],
            options={
                "verbose_name": "TTS额度流水",
                "verbose_name_plural": "TTS额度流水",
                "ordering": ["-created_at"],
            },
        ),
    ]
