# Generated by Django 5.0 on 2026-03-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0009_ttsorder_user_ttscreditaccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ttscreditrechargeorder",
            name="payment_error",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="支付错误信息"
            ),
        ),
        migrations.AddField(
            model_name="ttscreditrechargeorder",
            name="wechat_code_url",
            field=models.TextField(blank=True, verbose_name="微信支付二维码链接"),
        ),
        migrations.AddField(
            model_name="ttscreditrechargeorder",
            name="wechat_openid",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="支付用户OpenID"
            ),
        ),
        migrations.AddField(
            model_name="ttscreditrechargeorder",
            name="wechat_prepay_id",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="微信预支付ID"
            ),
        ),
    ]
