# Generated by Django 5.0 on 2026-03-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0010_ttscreditrechargeorder_payment_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ttscreditrechargeorder",
            name="payment_proof",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tts_recharge_proofs/",
                verbose_name="付款截图",
            ),
        ),
        migrations.AddField(
            model_name="ttscreditrechargeorder",
            name="payment_proof_uploaded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="付款截图上传时间"
            ),
        ),
    ]
