# Generated by Django 5.0 on 2026-03-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0011_ttscreditrechargeorder_payment_proof_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ttscreditaccount",
            name="is_unlimited",
            field=models.BooleanField(default=False, verbose_name="是否无限额度"),
        ),
    ]
