# Generated by Django 5.0 on 2026-03-13 17:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0014_ttsorder_cancel_requested"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_key",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="页面标识"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="页面标题")),
                ("path", models.CharField(max_length=255, verbose_name="页面路径")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "专栏页",
                "verbose_name_plural": "专栏页",
                "ordering": ["-view_count", "title"],
            },
        ),
        migrations.CreateModel(
            name="ColumnDailyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="日期"
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_views",
                        to="tools.columnpage",
                        verbose_name="专栏页",
                    ),
                ),
            ],
            options={
                "verbose_name": "专栏页日浏览",
                "verbose_name_plural": "专栏页日浏览",
                "ordering": ["-date", "-count"],
                "unique_together": {("column", "date")},
            },
        ),
    ]
